export const producs = [
    {
      id: 1,
      produto: "Camiseta",
      quantidade: 10,
      descricao: "Camiseta de algodão",
      preco: 20.99,
    },
    {
      id: 2,
      produto: "Calça Jeans",
      quantidade: 5,
      descricao: "Calça jeans masculina",
      preco: 39.99,
    },
    {
      id: 3,
      produto: "Tênis",
      quantidade: 8,
      descricao: "Tênis esportivo",
      preco: 59.99,
    },
    {
      id: 4,
      produto: "Boné",
      quantidade: 15,
      descricao: "Boné com aba curva",
      preco: 9.99,
    },
    {
      id: 5,
      produto: "Óculos de Sol",
      quantidade: 3,
      descricao: "Óculos de sol polarizado",
      preco: 29.99,
    },
    {
      id: 6,
      produto: "Relógio",
      quantidade: 12,
      descricao: "Relógio analógico",
      preco: 49.99,
    },
    {
      id: 7,
      produto: "Bolsa",
      quantidade: 7,
      descricao: "Bolsa feminina",
      preco: 34.99,
    },
    {
      id: 8,
      produto: "Chapéu",
      quantidade: 20,
      descricao: "Chapéu de palha",
      preco: 14.99,
    },
    {
      id: 9,
      produto: "Cinto",
      quantidade: 9,
      descricao: "Cinto de couro",
      preco: 19.99,
    },
    {
      id: 10,
      produto: "Moletom",
      quantidade: 6,
      descricao: "Moletom com capuz",
      preco: 29.99,
    },
    {
      id: 11,
      produto: "Sapato",
      quantidade: 4,
      descricao: "Sapato social masculino",
      preco: 69.99,
    },
    {
      id: 12,
      produto: "Saia",
      quantidade: 11,
      descricao: "Saia estampada",
      preco: 24.99,
    },
    {
      id: 13,
      produto: "Shorts",
      quantidade: 18,
      descricao: "Shorts jeans",
      preco: 17.99,
    },
    {
      id: 14,
      produto: "Blusa",
      quantidade: 13,
      descricao: "Blusa manga longa",
      preco: 22.99,
    },
    {
      id: 15,
      produto: "Jaqueta",
      quantidade: 7,
      descricao: "Jaqueta corta-vento",
      preco: 39.99,
    },
    {
      id: 16,
      produto: "Mochila",
      quantidade: 8,
      descricao: "Mochila escolar",
      preco: 27.99,
    },
    {
      id: 17,
      produto: "Vestido",
      quantidade: 14,
      descricao: "Vestido de festa",
      preco: 49.99,
    },
    {
      id: 18,
      produto: "Gravata",
      quantidade: 10,
      descricao: "Gravata clássica",
      preco: 12.99,
    },
    {
      id: 19,
      produto: "Luvas",
      quantidade: 5,
      descricao: "Luvas de couro",
      preco: 9.99,
    },
    {
      id: 20,
      produto: "Meias",
      quantidade: 22,
      descricao: "Meias esportivas",
      preco: 5.99,
    },
    {
      id: 21,
      produto: "Carteira",
      quantidade: 17,
      descricao: "Carteira de couro",
      preco: 14.99,
    },
    {
      id: 22,
      produto: "Blazer",
      quantidade: 3,
      descricao: "Blazer masculino",
      preco: 79.99,
    },
    {
      id: 23,
      produto: "Lenço",
      quantidade: 9,
      descricao: "Lenço estampado",
      preco: 7.99,
    },
    {
      id: 24,
      produto: "Colar",
      quantidade: 6,
      descricao: "Colar de pérolas",
      preco: 19.99,
    },
    {
      id: 25,
      produto: "Anel",
      quantidade: 12,
      descricao: "Anel de prata",
      preco: 29.99,
    },
    {
      id: 26,
      produto: "Brinco",
      quantidade: 15,
      descricao: "Brinco de ouro",
      preco: 39.99,
    },
    {
      id: 27,
      produto: "Pulseira",
      quantidade: 8,
      descricao: "Pulseira de couro",
      preco: 24.99,
    },
    {
      id: 28,
      produto: "Relógio Inteligente",
      quantidade: 4,
      descricao: "Relógio smartwatch",
      preco: 99.99,
    },
    {
      id: 29,
      produto: "Perfume",
      quantidade: 10,
      descricao: "Perfume masculino",
      preco: 49.99,
    },
    {
      id: 30,
      produto: "Creme Facial",
      quantidade: 7,
      descricao: "Creme hidratante",
      preco: 19.99,
    },
  ];